CREATE TABLE IF NOT EXISTS projects(id TEXT PRIMARY KEY,code TEXT NOT NULL UNIQUE,name TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',status TEXT NOT NULL,period_start TEXT,period_end TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS territories(id TEXT PRIMARY KEY,parent_id TEXT REFERENCES territories(id),kind TEXT NOT NULL,code TEXT,name TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS project_groups(id TEXT PRIMARY KEY,project_id TEXT NOT NULL REFERENCES projects(id),code TEXT NOT NULL,label TEXT NOT NULL,external_reference TEXT,created_at TEXT NOT NULL,UNIQUE(project_id,code));
CREATE TABLE IF NOT EXISTS units(id TEXT PRIMARY KEY,project_id TEXT NOT NULL REFERENCES projects(id),territory_id TEXT NOT NULL REFERENCES territories(id),project_group_id TEXT REFERENCES project_groups(id),code TEXT NOT NULL,name TEXT NOT NULL,unit_type TEXT NOT NULL,status TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,UNIQUE(project_id,code));
CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,login TEXT NOT NULL UNIQUE,display_name TEXT NOT NULL,password_hash TEXT NOT NULL,system_role TEXT NOT NULL CHECK(system_role IN('admin','user')),active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS project_memberships(project_id TEXT NOT NULL REFERENCES projects(id),user_id TEXT NOT NULL REFERENCES users(id),role TEXT NOT NULL CHECK(role IN('admin','coordinator','researcher','technician','viewer')),created_at TEXT NOT NULL,PRIMARY KEY(project_id,user_id));
CREATE TABLE IF NOT EXISTS sessions(id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),secret_hash TEXT NOT NULL,csrf_hash TEXT NOT NULL,expires_at TEXT NOT NULL,revoked_at TEXT,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS source_documents(id TEXT PRIMARY KEY,project_id TEXT REFERENCES projects(id),title TEXT NOT NULL,kind TEXT NOT NULL,external_name TEXT,sha256 TEXT,reference_period TEXT,provenance_status TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS activities(id TEXT PRIMARY KEY,project_id TEXT NOT NULL REFERENCES projects(id),unit_id TEXT REFERENCES units(id),kind TEXT NOT NULL,title TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',occurred_at TEXT,status TEXT NOT NULL,created_by TEXT REFERENCES users(id),created_at TEXT NOT NULL,updated_at TEXT NOT NULL,revision INTEGER NOT NULL DEFAULT 1,deleted_at TEXT);
CREATE TABLE IF NOT EXISTS observations(id TEXT PRIMARY KEY,activity_id TEXT NOT NULL REFERENCES activities(id),unit_id TEXT REFERENCES units(id),topic TEXT NOT NULL,statement TEXT NOT NULL,observation_kind TEXT NOT NULL,epistemic_status TEXT NOT NULL,observed_at TEXT,source_id TEXT REFERENCES source_documents(id),source_locator TEXT,created_by TEXT REFERENCES users(id),validation_status TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,revision INTEGER NOT NULL DEFAULT 1,deleted_at TEXT);
CREATE TABLE IF NOT EXISTS measurements(id TEXT PRIMARY KEY,observation_id TEXT NOT NULL REFERENCES observations(id),quantity REAL NOT NULL,unit TEXT NOT NULL,method TEXT NOT NULL,quality_status TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS attendance_aggregates(id TEXT PRIMARY KEY,activity_id TEXT NOT NULL UNIQUE REFERENCES activities(id),total INTEGER NOT NULL CHECK(total>=0),women INTEGER CHECK(women>=0),men INTEGER CHECK(men>=0),youth INTEGER CHECK(youth>=0),source_id TEXT NOT NULL REFERENCES source_documents(id),source_locator TEXT NOT NULL,quality_status TEXT NOT NULL,revision INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS evidence_files(id TEXT PRIMARY KEY,project_id TEXT NOT NULL REFERENCES projects(id),observation_id TEXT REFERENCES observations(id),activity_id TEXT REFERENCES activities(id),path_relative TEXT NOT NULL UNIQUE,original_name TEXT NOT NULL,mime TEXT NOT NULL,bytes INTEGER NOT NULL CHECK(bytes>=0),sha256 TEXT NOT NULL,uploaded_by TEXT NOT NULL REFERENCES users(id),created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS action_items(id TEXT PRIMARY KEY,project_id TEXT NOT NULL REFERENCES projects(id),activity_id TEXT REFERENCES activities(id),unit_id TEXT REFERENCES units(id),title TEXT NOT NULL,details TEXT NOT NULL DEFAULT '',status TEXT NOT NULL,priority TEXT NOT NULL,due_at TEXT,responsible_user_id TEXT REFERENCES users(id),created_by TEXT REFERENCES users(id),created_at TEXT NOT NULL,updated_at TEXT NOT NULL,revision INTEGER NOT NULL DEFAULT 1,deleted_at TEXT);
CREATE TABLE IF NOT EXISTS report_runs(id TEXT PRIMARY KEY,project_id TEXT NOT NULL REFERENCES projects(id),report_kind TEXT NOT NULL,parameters_json TEXT NOT NULL,data_revision_or_snapshot TEXT NOT NULL,generated_by TEXT NOT NULL REFERENCES users(id),generated_at TEXT NOT NULL,rule_version TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS audit_events(id TEXT PRIMARY KEY,actor_id TEXT REFERENCES users(id),project_id TEXT REFERENCES projects(id),entity_type TEXT NOT NULL,entity_id TEXT NOT NULL,action TEXT NOT NULL,event_at TEXT NOT NULL,before_json TEXT,after_json TEXT,request_id TEXT,prev_hash TEXT NOT NULL,event_hash TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_units_project ON units(project_id); CREATE INDEX IF NOT EXISTS idx_activities_project ON activities(project_id); CREATE INDEX IF NOT EXISTS idx_obs_activity ON observations(activity_id); CREATE INDEX IF NOT EXISTS idx_actions_project ON action_items(project_id); CREATE INDEX IF NOT EXISTS idx_sessions_secret ON sessions(secret_hash);

